version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 5
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authentication"
      update-types: ["version-update:semver-major"]
    - dependency-name: "Microsoft.AspNetCore.Http.Abstractions"
      update-types: ["version-update:semver-major"]
    - dependency-name: "Microsoft.AspNetCore.TestHost"
      update-types: ["version-update:semver-major"]
    - dependency-name: "Microsoft.Extensions.Options.ConfigurationExtensions"
      update-types: ["version-update:semver-major"]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 5
