<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>ASP.NET Core middleware that enables an application to support basic authentication.</Description>
        <PackageTags>aspnetcore;authentication;security;basicauth</PackageTags>
        <Configurations>Debug;Release;CodeQL</Configurations>
        <TargetFrameworks>netstandard2.0;net6.0;net8.0;net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
    </PropertyGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.AspNetCore.Authentication" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="System.Security.Cryptography.Xml" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
